#服务名称
spring:
  application:
    name: config-server

#服务的端口号
server:
  port: 9100

#指定注册中心地址
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/